# ---------------------------------------------------------------------
# Water Tank Level Sensor
# Hardware: Seeed XIAO ESP32-C6 8MB
# Sensors: JSN-RS04t
# Autor: Roland Ortner
# Date: 2024-09-07
# Uptime, WiFi Signal, 
# ---------------------------------------------------------------------

substitutions:
  devicename: "water-tank"
  friendlyname: "Water Tank Level"
  config_version: "2024.09.19.001"
  accuracy: "2"

esphome:
  name: "${devicename}"
  friendly_name: "${friendlyname}"
  comment: Water tank level with Seeed XIAO ESP32C6
  area: Garten

esp32:
  board: esp32-c6-devkitc-1 # esp32-c6-devkitc-1
  variant: esp32c6
  flash_size: 4MB
  framework:
    type: esp-idf
    #version: 5.1.2
    version: 5.3.1
    #platform_version: 6.5.0
    platform_version: 6.8.1
    #source: https://github.com/tasmota/esp-idf/releases/download/v5.1.2.240221/esp-idf-v5.1.2.zip
    source: https://github.com/tasmota/esp-idf/releases/download/v5.3.1/esp-idf-v5.3.1.zip
    sdkconfig_options:
      CONFIG_ESPTOOLPY_FLASHSIZE_4MB: y

external_components:
  - source:
      # https://github.com/lboue/esphome/blob/adc_oneshot/esphome/components/adc
      type: git
      url: https://github.com/lboue/esphome
      ref: adc_oneshot
    components: [ adc ]
    refresh: 0s
    
# Enable logging
logger:
  level: DEBUG

# Enable Over the Air (OTA) updates
ota:
  - platform: esphome
    password: ""

# Enable WiFi connection
wifi:
  ssid: "FRITZ!Box 7590 XK"
  password: "10235391332341688512"
  fast_connect: true
  ap:
    ssid: "Water-Tank Fallback Hotspot"
    password: "LevrhqZgmMx9"

web_server:
  port: 80
  version: 3

# UART mode
uart:
  - id: uart_distance
    tx_pin: GPIO16 # Tx Echo D6 GPIO16
    rx_pin: GPIO17 # Rx Trig D7 GPIO17 
    baud_rate: 9600
    stop_bits: 1 
    #rx_buffer_size: 4
    #debug:
    #  direction: BOTH
    #  dummy_receiver: false
    #  after:
    #    delimiter: "\n"
    #  sequence:
    #    - lambda: UARTDebug::log_string(direction, bytes);

text_sensor:
  - platform: template
    name: "Configuration"
    icon: mdi:information-outline
    lambda: |-
      return {"${config_version}"};
    entity_category: "config"
  
  - platform: version
    name: "ESPHome Version"
    hide_timestamp: true
    disabled_by_default: false
    icon: mdi:information-outline
    entity_category: diagnostic

  - platform: wifi_info
    ip_address:
      name: "IP-Address"
      icon: mdi:ip
    ssid:
      name: "SSID"
      icon: mdi:wifi
    bssid:
      name: "BSSID"
      icon: mdi:network-outline
    mac_address:
      name: "MAC-Address"
      icon: mdi:network

  - platform: template
    name: Uptime
    entity_category: "config"
    lambda: |-
      int seconds = (id(uptime_seconds).state);
      int days = seconds / (24 * 3600);
      seconds = seconds % (24 * 3600);
      int hours = seconds / 3600;
      seconds = seconds % 3600;
      int minutes = seconds /  60;
      seconds = seconds % 60;
      std::string output = "";
      if ( days ) {
        output += esphome::to_string(days) + "d ";
      }
      if (hours) {
        output += esphome::to_string(hours) + "h ";
      }
      if (minutes) {
        output += esphome::to_string(minutes) + "m ";
      }
      if (seconds) {
        output += esphome::to_string(seconds) +"s";
      }
      return output;
    icon: mdi:clock-start
    update_interval: 60s

sensor:
  - platform: uptime
    id: uptime_seconds

  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    id: wifi_signal_db
    name: "WiFi Signal Strength"
    icon: mdi:wifi-strength-2 
    unit_of_measurement: 'dBm'
    entity_category: "diagnostic"
    update_interval: 60s

  - platform: wifi_signal
    id: wifi_signal_percent
    name: "WiFi Signal"
    icon: mdi:wifi 
    unit_of_measurement: '%'
    entity_category: "diagnostic"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    device_class: ""
    update_interval: 60s

  # voltage monitor of battery with 220 k resistors on A0 (3.7V)
  - platform: adc
    id: battery_voltage
    name: "Battery Voltage"
    icon: mdi:battery-high 
    entity_category: "diagnostic"
    pin: 0 # D0 A0 with voltage devider using 220k resistors to GND & VCC
    accuracy_decimals: 2
    update_interval: 60s
    filters:
      - multiply: 2.00

  # battery level in percent
  - platform: template 
    id: battery_level
    name: "Battery Level"
    icon: mdi:battery
    entity_category: "diagnostic"
    unit_of_measurement: '%'
    update_interval: 60s
    lambda: |-
      return ((id(battery_voltage).state /3.70) * 100.00);

  # water level sensor AJ-SR04M (https://markus-haack.com/watertank-esphome/)
  - platform: jsn_sr04t # "ultrasonic" / "jsn_sr04t"
    #model: "aj_sr04m" # AJ-SR04M does only work with mode jsn_sr04t!
    # error: [W][jsn_sr04t.sensor:054]: checksum failed: c6 != c5
    name: "Distance"
    id: distance
    uart_id: uart_distance
    accuracy_decimals: 1
    filters: 
      - filter_out: nan
      - lambda: return (id(distance).state / 100); # cm instead of m
    update_interval: 10s

  # water volume depending on the water level 
  # Regenwasser-Flachtank Platin 1500 l (V = 0,00003452x^4 - 0,00919289x^3 + 0,64686665x^2 + 9,36145409x)
  - platform: template
    id: volume
    name: Volume (L)
    icon: mdi:car-brake-fluid-level
    unit_of_measurement: "l"
    lambda: return (0.00003452 * pow(id(distance).state, 4) - 0.00919289 * pow(id(distance).state, 3) + 0.64686665 * pow(id(distance).state, 2) + 9.36145409 * id(distance).state);
    filters:
      - filter_out: nan
    update_interval: 10s

  - platform: template
    id: volume_percent
    name: Volume (%)
    icon: mdi:car-brake-fluid-level
    unit_of_measurement: "%"
    lambda: return ((1500 / id(volume).state) * 100);  
    filters:
      - filter_out: nan
    update_interval: 10s

mqtt:
  id: mqtt_client
  broker: c66d20867a5f42d0823836d4f0f55daa.s1.eu.hivemq.cloud
  port: 8883
  topic_prefix: water_tank
  #discovery: false
  #discovery_prefix: homeassistant
  username: esp32c6
  password: WfYHi#;8re2Q*3y
  #skip_cert_cn_check: true
  #birth_message:
  #  topic: /water_tank
  #  payload: online
  #will_message:
  #  topic: /water_tank
  #  payload: offline
  certificate_authority: |
    -----BEGIN CERTIFICATE-----
    MIIFazCCA1OgAwIBAgIRAIIQz7DSQONZRGPgu2OCiwAwDQYJKoZIhvcNAQELBQAw
    TzELMAkGA1UEBhMCVVMxKTAnBgNVBAoTIEludGVybmV0IFNlY3VyaXR5IFJlc2Vh
    cmNoIEdyb3VwMRUwEwYDVQQDEwxJU1JHIFJvb3QgWDEwHhcNMTUwNjA0MTEwNDM4
    WhcNMzUwNjA0MTEwNDM4WjBPMQswCQYDVQQGEwJVUzEpMCcGA1UEChMgSW50ZXJu
    ZXQgU2VjdXJpdHkgUmVzZWFyY2ggR3JvdXAxFTATBgNVBAMTDElTUkcgUm9vdCBY
    MTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAK3oJHP0FDfzm54rVygc
    h77ct984kIxuPOZXoHj3dcKi/vVqbvYATyjb3miGbESTtrFj/RQSa78f0uoxmyF+
    0TM8ukj13Xnfs7j/EvEhmkvBioZxaUpmZmyPfjxwv60pIgbz5MDmgK7iS4+3mX6U
    A5/TR5d8mUgjU+g4rk8Kb4Mu0UlXjIB0ttov0DiNewNwIRt18jA8+o+u3dpjq+sW
    T8KOEUt+zwvo/7V3LvSye0rgTBIlDHCNAymg4VMk7BPZ7hm/ELNKjD+Jo2FR3qyH
    B5T0Y3HsLuJvW5iB4YlcNHlsdu87kGJ55tukmi8mxdAQ4Q7e2RCOFvu396j3x+UC
    B5iPNgiV5+I3lg02dZ77DnKxHZu8A/lJBdiB3QW0KtZB6awBdpUKD9jf1b0SHzUv
    KBds0pjBqAlkd25HN7rOrFleaJ1/ctaJxQZBKT5ZPt0m9STJEadao0xAH0ahmbWn
    OlFuhjuefXKnEgV4We0+UXgVCwOPjdAvBbI+e0ocS3MFEvzG6uBQE3xDk3SzynTn
    jh8BCNAw1FtxNrQHusEwMFxIt4I7mKZ9YIqioymCzLq9gwQbooMDQaHWBfEbwrbw
    qHyGO0aoSCqI3Haadr8faqU9GY/rOPNk3sgrDQoo//fb4hVC1CLQJ13hef4Y53CI
    rU7m2Ys6xt0nUW7/vGT1M0NPAgMBAAGjQjBAMA4GA1UdDwEB/wQEAwIBBjAPBgNV
    HRMBAf8EBTADAQH/MB0GA1UdDgQWBBR5tFnme7bl5AFzgAiIyBpY9umbbjANBgkq
    hkiG9w0BAQsFAAOCAgEAVR9YqbyyqFDQDLHYGmkgJykIrGF1XIpu+ILlaS/V9lZL
    ubhzEFnTIZd+50xx+7LSYK05qAvqFyFWhfFQDlnrzuBZ6brJFe+GnY+EgPbk6ZGQ
    3BebYhtF8GaV0nxvwuo77x/Py9auJ/GpsMiu/X1+mvoiBOv/2X/qkSsisRcOj/KK
    NFtY2PwByVS5uCbMiogziUwthDyC3+6WVwW6LLv3xLfHTjuCvjHIInNzktHCgKQ5
    ORAzI4JMPJ+GslWYHb4phowim57iaztXOoJwTdwJx4nLCgdNbOhdjsnvzqvHu7Ur
    TkXWStAmzOVyyghqpZXjFaH3pO3JLF+l+/+sKAIuvtd7u+Nxe5AW0wdeRlN8NwdC
    jNPElpzVmbUq4JUagEiuTDkHzsxHpFKVK7q4+63SM1N95R1NbdWhscdCb+ZAJzVc
    oyi3B43njTOQ5yOf+1CceWxG1bQVs5ZufpsMljq4Ui0/1lvh+wjChP4kqKOJ2qxq
    4RgqsahDYVvTH9w7jXbyLeiNdd8XM2w9U/t7y0Ff/9yi0GE44Za4rF2LN9d11TPA
    mRGunUHBcnWEvgJBQl9nJEiU0Zsnvgc/ubhPgXRR4Xq37Z0j4r7g1SgEEzwxA57d
    emyPxgcYxn/eR44/KJ4EBs+lVDR3veyJm+kXQ99b21/+jh5Xos1AnX5iItreGCc=
    -----END CERTIFICATE-----

# deep sleep for 2min and run vo 30sec
#deep_sleep:
#  run_duration: 30s
#  sleep_duration: 2min    