# ---------------------------------------------------------------------
# Water Tank Level Sensor
# Hardware: Seeed XIAO ESP32-C6 8MB
# Sensors: JSN-RS04t
# Autor: Roland Ortner
# Date: 2024-09-07
# ---------------------------------------------------------------------

esphome:
  name: water-tank
  friendly_name: Water Tank Level
  comment: Water tank level with Seeed XIAO ESP32C6
  area: Garten

esp32:
  board: esp32-c6-devkitc-1
  variant: esp32c6
  flash_size: 4MB
  framework:
    type: esp-idf
    #version: 5.1.2
    version: 5.3.1
    #platform_version: 6.5.0
    platform_version: 6.8.1
    #source: https://github.com/tasmota/esp-idf/releases/download/v5.1.2.240221/esp-idf-v5.1.2.zip
    source: https://github.com/tasmota/esp-idf/releases/download/v5.3.1/esp-idf-v5.3.1.zip
    sdkconfig_options:
      CONFIG_ESPTOOLPY_FLASHSIZE_4MB: y
    
# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  password: ""

ota:
  - platform: esphome
    password: ""

wifi:
  ssid: "FRITZ!Box 7590 XK"
  password: "10235391332341688512"
  #fast_connect: true
  ap:
    ssid: "Water-Tank Fallback Hotspot"
    password: "LevrhqZgmMx9"

captive_portal:

web_server:
  port: 80

sensor:
  - platform: uptime
    name: "Uptime"
    type: seconds

  - platform: wifi_signal
    name: "Wifi"
    update_interval: 600s
    unit_of_measurement: '%'
    filters:
      lambda: |-
        if (x <= -100) {
          return 0;
        } else {
          if (x >= -50) {
            return 100;
          } else {
            return 2 * (x + 100);
          }
        }
